### ISSUE TITLE
DocType element default value

### ISSUE THREAD

**Issue by hubblec4** [ietf-wg-cellar/ebml-specification#400]
In the Ebml.xml is 'ebml' the default value.
> <element name="DocType" path="\EBML\DocType" id="0x4282" type="string" default="ebml" length="&gt;0" minOccurs="1" maxOccurs="1"

In the [RFC datatracker](https://datatracker.ietf.org/doc/rfc8794/?include_text=1) is no default value assigend

> 11.2.6.  DocType Element
   name:  DocType
   path:  "\EBML\DocType"
   id:  0x4282
   minOccurs:  1
   maxOccurs:  1
   length:  >0
   type:  String

And I have read on another place(can't remember where) that 'matroska' is used as default.
In my EBML project I have also 'matroska' as default value declared.

What is the correct default value?

**Comment by hubblec4** [comment]
Found where 'matroska' is used for the DocType default value.
There was an issue opened for that a long time ago. #74

**Comment by robUx4** [comment]
Indeed, the text is correct and the XML is not.

**Comment by hubblec4** [comment]
OK. good to know that this element have no default value.

**Comment by hubblec4** [comment]
Is this really a good idea to remove the default value?
I have seen in older mkv files there is no DocType element. Such files now are no more recognized as Matroska files, because the DocType value(I mean the element type default value) is now an empty String.

Why not using 'matroska' as default value. Matroska is the first project which uses EBML.

**Comment by JeromeMartinez** [comment]
I like the idea to separate well Matroska (specific usage of EBML) and EBML itself (no preference about a format using it, generic).

We could have a notice in Matroska that a Matroska may try to parse a file with empty String in DocType

**Comment by robUx4** [comment]
An empty DocType is not allowed in EBML. That would allow invalid EBML content (and so having special cases in EBML parsers).

**Comment by JeromeMartinez** [comment]
> An empty DocType is not allowed in EBML.

Not empty, but in the past there was a default value ("matroska"), e.g. in https://web.archive.org/web/20100208194332/http://matroska.org/technical/specs/index.html

IMO it is good to remove the default value for a more generic EBML (and the current default value is definitely wrong), but Matroska spec should have a note somewhere about some legacy Matroska without DocType content which may exist because it was considered as fine in the past.

**Comment by hubblec4** [comment]
> An empty DocType is not allowed in EBML. That would allow invalid EBML content (and so having special cases in EBML parsers).

When we remove the default value, then there is alwasy the DocType value an empty String -> this is the type default value.

**Comment by robUx4** [comment]
Technically the EBML Schema already has enforced EBML constraints at the top
```xml
  <!-- constraints on EBML Header Elements -->
  <element name="EBMLMaxIDLength" path="\EBML\EBMLMaxIDLength" id="0x42F2" type="uinteger" range="4" default="4" minOccurs="1" maxOccurs="1"/>
  <element name="EBMLMaxSizeLength" path="\EBML\EBMLMaxSizeLength" id="0x42F3" type="uinteger" range="1-8" default="8" minOccurs="1" maxOccurs="1"/>
```

We can add the same constraint with a default value for DocType. This doesn't produce text in the output RFC though. We could have some text saying this. But it should be a bit restrictive IMO: having the Matroska MIME type or a .mkv/.mka file extension. And it should be said that it's only for legacy/compatibility reasons.
