### ISSUE TITLE
EBML ID 0x80 is marked invalid/reserved but it's used in Matroska

### ISSUE THREAD

**Issue by robUx4** [ietf-wg-cellar/ebml-specification#407]
As pointed out by [Paul Foley](https://mailarchive.ietf.org/arch/msg/cellar/z_INjU-Vc9FOTDZs9AhdRRjrIig/), the 0x80 is EBML ID is said to be invalid in the [RFC text](https://datatracker.ietf.org/doc/html/rfc8794#section-5):

> The bits of the VINT_DATA component of the Element ID MUST NOT be all "0" values or all "1" values.

But in Matroska we use 0x80 for `ChapterDisplay`.

I think the all 0 rules should be removed. In particular because 0x80 is the value that should be used when all VINT_DATA bits are 0, per this rule:

> The VINT_DATA component of the Element ID MUST be encoded at the shortest valid length.

Changing this text means also editing the IANA registry which lists all the variants of 0 bits as reserved.

**Comment by hubblec4** [comment]
That's indeed not nice.
But luckly the VINT of an element ID is fully used and not the integer value of the VINT.
Yes, the integer value of VINT "0x80" is 0(zero), but this value is not used for the element ID.

I agree with removing the "all 0 bits as reserved" restriction.
